blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('myfirstpage', views.first_page, name='myfirstpage'),
    path('genericpage', views.generic_page, name='genericpage'),
    path('fibonacci/<int:num>', views.fibonacci_finder, name='fibonacci'),
    path('blogform', views.show_blog_form, name='show_blog_form'),
    path('blogform/addnew', views.add_blog_entry, name='add_blog_entry'),
    path('posts/<int:pk>', views.get_post, name='get_post'),
    path('allposts', views.get_all_posts, name='get_all_posts')
]

gradebook/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('student/<int:rollno>', views.student_detail, name='student_detail'),
    path('student/add', views.add_student, name='add_student'),
    path('student/<int:rollno>/addmark', views.add_student_mark, name='add_student_mark'),
    path('student/bulk-upload-form', views.bulk_upload_form, name='bulk_upload_form'),
    path('student/bulk-upload', views.student_bulk_upload, name='student_bulk_upload'),
    path('student/all', views.student_list, name='student_list'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('gradebook/', include('gradebook.urls'))
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=256)
    heading = models.CharField(max_length=1000)
    text = models.TextField(max_length=100000)

    def __repr__(self):
        return f'Title: {self.title}, Heading:{self.heading}'

gradebook/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=256)
    rollno = models.IntegerField()

    def total_marks(self):
        marks = Marks.objects.filter(student=self)
        return sum([mark.score for mark in marks])
    
    def grade(self):
        grade = 'UNDEFINED'
        marks = Marks.objects.filter(student=self)
        if len(marks) != 0:
            avg = self.total_marks() / len(marks)
            grades = {(90, 100): 'A', (80, 90): 'A-', (70, 80): 'B', (60, 70): 'B-', (40, 60): 'C', (0, 40): 'F'}
            for lower, upper in grades.keys():
                if lower < avg <= upper:
                    grade = grades[(lower, upper)]
        return grade
        

class Marks(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    score = models.IntegerField()
    subject = models.CharField(max_length=256)

gradebook/forms.py
from django import forms
from django.core.exceptions import ValidationError

class StudentForm (forms.Form):
    name = forms.CharField(label='Student name', max_length=256)
    rollno = forms.IntegerField(label='Roll number', max_value=1000000)

    def clean(self):
        roll_data = self.cleaned_data['rollno']
        name_data = self.cleaned_data['name']
        if name_data == 'dinesh' and roll_data != 7:
            raise ValidationError('Dinesh is only 007')

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post

# Create your views here.
def nth_fibo(n):
    if n == 1 or n == 2:
        return 1
    return nth_fibo(n - 1) + nth_fibo(n - 2)

def fibonacci_finder(request, num):
    x = [nth_fibo(n) for n in range(1, num + 1)]
    context = {'fibonaccis': x}
    return render(request, 'blog/fibonaccis.html', context)

def first_page(request):
    x = 2 ** 0.5
    context = {'topsecret': x}
    return render(request, 'blog/firstpage.html', context)

def generic_page(request):
    title = "Your title here"
    heading = "Your heading here"
    text = "Your text here"
    context = {'title': title, 'heading': heading, 'text': text}
    return render(request, 'blog/genericpage.html', context)

def show_blog_form(request):
    return render(request, 'blog/blogform.html')

def add_blog_entry(request):
    title = request.POST['title']
    heading = request.POST['heading']
    text = request.POST['text']
    p = Post(title=title, heading=heading, text=text)
    p.save()
    return redirect('blog:get_post', p.pk)

def get_post(request, pk):
    p = Post.objects.get(pk=pk)
    context = {'title': p.title, 'heading': p.heading, 'text': p.text}
    return render(request, 'blog/genericpage.html', context)

def get_all_posts(request):
    posts = Post.objects.all()
    return render(request, 'blog/allposts.html', {'posts': posts})

gradebook/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from .models import Student, Marks
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from .forms import StudentForm
# Create your views here.

@login_required(login_url='login')
def student_detail(request, rollno):
    s = Student.objects.get(rollno=rollno)
    context = {
        'student': s
    }
    return render(request, 'gradebook/student_detail.html', context)

@login_required(login_url='login')
def add_student(request):
    if request.method == 'POST':
        sf = StudentForm(request.POST)
        if sf.is_valid():
            student = Student.objects.create(
                name=sf.cleaned_data['name'],
                rollno=sf.cleaned_data['rollno'],
            )
            return redirect('student_detail', student.rollno)    
    else:
        sf = StudentForm()
    return render(request, 'gradebook/student_form.html', {'form': sf})   
            
    

@permission_required('gradebook.add_marks', login_url='login')
def add_student_mark(request, rollno):
    if request.method == 'GET':
        return HttpResponse("please use POST only on this endpoint")
    s = Student.objects.get(rollno=rollno)
    subject = request.POST['subject']
    score = request.POST['score']
    Marks.objects.create(
        student=s,
        subject=subject,
        score=score
    )
    return redirect('student_detail', s.rollno)

@login_required(login_url='login')
def student_bulk_upload(request):
    uploaded_file = request.FILES['bulkmarks']
    contents = str(uploaded_file.read())
    lines = contents.split('\\n')
    lines[0] = lines[0][2:]
    del lines[-1]
    for line in lines:
        contents = line.split(';')
        rollno = contents[0]
        name = contents[1]
        s, created = Student.objects.get_or_create(name=name, rollno=rollno)
        for item in contents[2:]:
            item = item.replace(' ', '')
            item = item.replace('(', '')
            item = item.replace(')', '')
            subject, score = item.split(',')
            Marks.objects.get_or_create(student=s, subject=subject, score=score)
    return HttpResponse(lines)

@login_required(login_url='login')
def bulk_upload_form(request):
    return render(request, 'gradebook/bulk_student_upload.html')

@login_required(login_url='login')
def student_list(request):
    s = Student.objects.all()
    return render(request, 'gradebook/allstudents.html', {'students': s})

def login_view(request):
    if request.method == 'GET':
        return render(request, 'gradebook/login.html')
    if request.method == 'POST':
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            redirect_url = request.POST.get('next')
            print(redirect_url)
            if redirect_url not in ['', None]:
                return redirect(redirect_url)
            return redirect('student_list')
        else:
            return render(request, 'gradebook/login.html', {'message': 'Invalid credentials, try again'})
def logout_view(request):
    logout(request)
    return redirect('login')

blog/templates/blog/allposts.html
<!DOCTYPE html>
<html>
    <ul>
    {% for post in posts %}
        <li><a href="{% url 'blog:get_post' post.pk %}">{{post.heading}}</a></li>
    {% endfor %}
    </ul>
</html>

blog/templates/blog/blogform.html
<!DOCTYPE html>
<body>
    <form action="{% url 'blog:add_blog_entry' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" id="title" name="title">
        <label for="heading">Heading</label>
        <input type="text" id="heading" name="heading">
        <label for="text">Text</label>
        <input type="text" id="text" name="text">
        <input type="submit" value="Submit!">
    </form>
</body>

blog/templates/blog/fibonaccis.html
<!DOCTYPE html>
<html>
    <body>
        <h1>Fibonacci Sequence</h1>
        {% for number in fibonaccis %}
        {{number}}, 
        {% endfor %}
    </body>
</html>

blog/templates/blog/firstpage.html
<!DOCTYPE html>
    <html>
        <head>
            <title>Amazing!</title>
        </head>
        <body>
            <h1>Django Response:</h1>
            <p>We can write any string here</p>
            <p>And it gets automagically wrapped</p>
            <p>into the HTTP Response!</p>
            <p>Try clicking "view page source"</p>
            <p>Our top secret operation has resulted in : {{topsecret}}</p>
        </body>
    </html>

blog/templates/blog/genericpage.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{title}}</title>
    </head>
    <body>
        <h1>{{heading}}</h1>
        <p>{{text}}</p>
        <footer>Add your own: <a href="{% url 'blog:show_blog_form' %}">here</a></footer>
    </body>
</html>

gradebook/templates/gradebook/allstudents.html
<!DOCTYPE html>
<html>
    <body>
        {% if not user.is_authenticated %}
        <p>You need to login to access this page</p>
        <a href="{% url 'login' %}">Login here!</a>
        {% else %}
        <h3>All students:</h3>
        <ul>
        {% for student in students %}
            <li><a href="{% url 'student_detail' student.rollno %}">{{student.name}}</a></li>
        {% endfor %}
        </ul>
        <a href="{% url 'logout' %}">Log out</a>
        {% endif %}
    </body>
</html>

gradebook/templates/gradebook/bulk_student_upload.html
<!DOCTYPE html>
<html>
    <body>
        <h1>Bulk student upload</h1>
        <form method="POST" action="{% url 'student_bulk_upload' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="bulkmarks" >
            <input type="submit" value="submit">
        </form>
    </body>
</html>

gradebook/templates/gradebook/login.html
<!DOCTYPE html>
<html>
    <body>
        <h3>LOGIN</h3>
        <p>{{message}}</p>
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" id="username" name="username"><br/>
            <label for="password">Password</label>
            <input type="password" id="password" name="password">
            <input type="submit" value="Login">
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        </form>
    </body>
</html>

gradebook/templates/gradebook/student_detail.html
<!DOCTYPE html>
<html>
    <body>
        <h3>{{student.name}} details</h3>
        <table>
            <tr>
                <td>Subject</td>
                <td>Marks</td>
            </tr>
            {% for mark in student.marks_set.all %}
            <tr>
                <td>{{mark.subject}}</td>
                <td>{{mark.score}}</td>
            </tr>
            {% endfor %}
            <tr>
                <td>Total</td>
                <td>{{student.total_marks}}</td>
            </tr>
            <tr>
                <td>Grade</td>
                <td>{{student.grade}}</td>
            </tr>
            <tr>
                <form action="{% url 'add_student_mark' student.rollno%}" method="POST">
                    {% csrf_token %}
                    <td><input name="subject" type="text"></td>
                    <td><input name="score" type="text">
                    <input type="submit" value="Add mark!"></td>
                </form>
            </tr>
        </table>
    </body>
</html>

gradebook/templates/gradebook/student_form.html
<!DOCTYPE html>
<html>
    <body>
        <form action="{% url 'add_student' %}" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Add student">
        </form>
    </body>
</html>